name:                texel-tuner
version:             0.1.0.0
github:              "Osrepnay/trout"
license:             MIT
author:              "Osrepnay"
maintainer:          "example@example.com"
copyright:           "2025 Osrepnay"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/texel-tuner#readme>

dependencies:
- base >= 4.7 && < 5
- trout
- vector
- megaparsec
- text
- parallel
- transformers
- random-shuffle
- random
- split

language: GHC2021

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  texel-tuner-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - texel-tuner

tests:
  texel-tuner-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - texel-tuner
