module Main (main) where

import Data.Bifunctor (first)
import Data.Functor.Identity (Identity, runIdentity)
import Data.HashSet qualified as HS
import Data.Hashable (Hashable)
import Data.List (intercalate, maximumBy)
import Data.List.Split (chunksOf)
import Data.Maybe (fromJust)
import Data.Ord (comparing)
import Data.Text.IO qualified as TIO
import Data.Vector.Primitive qualified as PV
import PgnParse (parsePgns, playPgn)
import System.Environment (getArgs)
import System.Random (newStdGen)
import System.Random.Shuffle (shuffle')
import Text.Megaparsec (errorBundlePretty, parse)
import Text.Printf (printf)
import Trout.Game (Game (..), allDisquiets, inCheck, makeMove)
import Trout.Game.Board (Board (..))
import Trout.Game.Move (Move (..))
import Trout.Piece (colorSign)
import Trout.Search (seeOfUnquiet)
import Trout.Search.Eval (eval)
import Trout.Search.Worthiness (lossWorth, winWorth)
import Tuner
  ( StructuredTunables (..),
    Tunables,
    calcError,
    calculateWorthiness,
    newTunables,
    structurize,
    tuneEpoch,
  )

formatTunables :: Tunables -> String
formatTunables tunables =
  "piece-square tables:\n"
    ++ intercalate
      "\n\n"
      ( uncurry formatSet
          <$> zip
            [ "pawnMPST",
              "knightMPST",
              "bishopMPST",
              "rookMPST",
              "queenMPST",
              "kingMPST",
              "pawnEPST",
              "knightEPST",
              "bishopEPST",
              "rookEPST",
              "queenEPST",
              "kingEPST"
            ]
            [0 ..]
      )
    ++ "\n"
    ++ "mobility:\n"
    ++ formatMob
    ++ "\n"
    ++ "king safety:\n"
    ++ show safeties
    ++ "\n"
    ++ "passer mults:\n"
    ++ show passers
    ++ "\n"
    ++ "bishop pair:\n"
    ++ show bishop
    ++ "\n"
    ++ "tempo bonus:\n"
    ++ show tempo
  where
    intRound :: Double -> Int
    intRound = round

    roundAll = PV.map intRound
    roundTup (a, b) = (intRound a, intRound b)

    formatStr =
      intercalate
        "\n"
        [ "%s :: Vector Int",
          "%s = V.fromList $ concat $ reverse",
          "%s"
        ]
    formatSet name nthBoard = printf formatStr name name formattedBoard
      where
        twoDimBoard :: [[Int]]
        twoDimBoard =
          reverse $
            chunksOf 8 $
              PV.toList $
                roundAll $
                  PV.slice (nthBoard * 64) 64 tunables
        formattedBoard = "  [ " ++ intercalate ",\n    " (show <$> twoDimBoard) ++ "\n  ]"

    sTun = structurize tunables

    mobs = roundAll $ sTunableMobility sTun
    formatMob = "[" ++ intercalate ", " (show <$> PV.toList mobs) ++ "]"
    safeties = roundTup $ sTunableKingSafety sTun
    passers = roundTup $ sTunablePasserMults sTun
    bishop = roundTup $ sTunableBishopPair sTun
    tempo = intRound $ sTunableTempoBonus sTun

removeSingle :: (Eq a) => a -> [a] -> [a]
removeSingle _ [] = []
removeSingle r (x : xs)
  | r == x = xs
  | otherwise = x : removeSingle r xs

singleSelect :: [(Int, Move)] -> ((Int, Move), [(Int, Move)])
singleSelect moves = (best, removeSingle best moves)
  where
    best = maximumBy (comparing fst) moves

-- quiescence search that also returns leaf node
-- it's in readert st monad in real quie
-- and it was easier to jut wrap it in identity monad to keep the syntax
tracingQuie :: Double -> Double -> Game -> (Double, Game)
tracingQuie !alpha !beta !game = runIdentity $ do
  -- stand-pat from null-move observation (eval immediately = not moving)
  let staticEval = fromIntegral $ eval board
  if staticEval >= beta
    then pure (staticEval, game)
    else
      go
        staticEval
        game
        ( filter
            ((>= 0) . fst)
            ((\m -> (scoreMove m, m)) <$> allDisquiets board)
        )
  where
    board = gameBoard game

    -- seeOfUnquiet should always be Just for a move
    -- generated by allDisquiets
    scoreMove m = fromJust $ seeOfUnquiet board m

    go :: Double -> Game -> [(Int, Move)] -> Identity (Double, Game)
    go bestScore bestGame [] = pure (bestScore, bestGame)
    go bestScore bestGame moves = case makeMove game move of
      Just movedGame -> do
        let trueAlpha = max alpha bestScore
        let (score, g) = first negate $ tracingQuie (-beta) (-trueAlpha) movedGame
        if score >= beta
          then pure (score, g)
          else
            if score > bestScore
              then go score g movesRest
              else go bestScore bestGame movesRest
      Nothing -> go bestScore bestGame movesRest
      where
        ((_, move), movesRest) = singleSelect moves

quieWrapper :: Game -> (Double, Game)
quieWrapper game =
  first
    (* fromIntegral (colorSign (boardTurn (gameBoard game))))
    (tracingQuie (fromIntegral lossWorth) (fromIntegral winWorth) game)

fastNub :: (Hashable b) => (a -> b) -> [a] -> [a]
fastNub keyFunc xs =
  snd $
    foldl'
      ( \(set, accum) x ->
          let keyed = keyFunc x
           in if HS.member keyed set
                then (set, accum)
                else (HS.insert keyed set, x : accum)
      )
      (HS.empty, [])
      xs

main :: IO ()
main = do
  args <- getArgs
  let filename = case args of
        (x : _) -> x
        [] -> error "no file provided as argument"
  fileContents <- TIO.readFile filename
  let startingTunables = newTunables
  let parsed = parse parsePgns filename fileContents
  case parsed of
    Left err -> putStrLn (errorBundlePretty err)
    Right pgnGames -> do
      let take25 xs = do
            gen <- newStdGen
            pure $ take 25 (shuffle' xs (length xs) gen)
      allGames <- concat <$> traverse (take25 . playPgn) pgnGames
      let trimmedGames =
            filter
              ((\board -> not (inCheck (boardTurn board) (boardPieces board))) . gameBoard . fst)
              allGames
      let quiedGames = first (snd . quieWrapper) <$> trimmedGames
      let uniqueGames = fastNub (gameBoard . fst) quiedGames
      putStrLn $ "number of positions: " ++ show (length uniqueGames)
      putStrLn $ "positions trimmed: " ++ show (length allGames - length trimmedGames)
      putStrLn $ "duplicates removed: " ++ show (length quiedGames - length uniqueGames)
      -- let k = calcSigmoidK startingTunables uniqueGames
      let k = 0.0058
      putStrLn $ "k: " ++ show k

      let startingWorthiness = calculateWorthiness (fst <$> uniqueGames) startingTunables
      let startingNormFac = 100 / startingWorthiness PV.! 0
      let poop = 1000 / (PV.sum (PV.slice 0 64 startingTunables) / 48)
      print poop
      print startingWorthiness
      let normedStartingWorthiness = PV.map (* startingNormFac) startingWorthiness
      let normedStartingTunables = PV.map (* poop) startingTunables
      putStrLn $ formatTunables normedStartingTunables
      printf "worthiness: %s\n" (show normedStartingWorthiness)

      let keepTuning prevErr currTunables = do
            putStrLn $ "previous error: " ++ show prevErr
            putStrLn $ "previous tunables: " ++ show currTunables
            gen <- newStdGen
            let shuffledGames = shuffle' uniqueGames (length uniqueGames) gen
            let steppedTunables = tuneEpoch currTunables shuffledGames k 500000
            let newErr = calcError steppedTunables uniqueGames k
            if newErr > prevErr
              then pure currTunables
              else keepTuning newErr steppedTunables
      finalTunables <- keepTuning (calcError startingTunables uniqueGames k) startingTunables
      let worthiness = calculateWorthiness (fst <$> uniqueGames) finalTunables
      let normFac = 100 / worthiness PV.! 0
      let normedWorthiness = PV.map (* normFac) worthiness
      printf "worthiness: %s\n" (show normedWorthiness)
      let normed = PV.map (* normFac) finalTunables
      putStrLn $ formatTunables normed
